// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// `vercel env pull` schreibt nach .env.local (wie Next.js), die Prisma CLI lädt
// standardmäßig aber nur .env — deshalb hier explizit beide laden, .env.local zuerst.
config({ path: ".env.local" });
config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrationen laufen über die direkte (ungepoolte) Verbindung, da PgBouncer-Pooling
    // (z. B. bei Neon) mit den DDL-Advisory-Locks von `migrate` kollidieren kann.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
